spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/library?useSSL=false
      username: root
      password: xiaoHAI123.
      driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zjh.pojo

#分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
